# -*- coding: utf-8 -*-
"""Create your own decorator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XwWoxEk4fKS6uRRAKSr4VIrVFeqQRdqH
"""

import time
# We define the decorator
def calculate_execution_time(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        execution_time = end_time - start_time
        print(f"Execution time of {func.__name__}: {execution_time} seconds")
        return result
    return wrapper

# Our function whose duration is measured using the decorator
def my_function():
    time.sleep(20)
    print("Completed")
my_function()